// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-stories.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.49.8";
import { z } from "npm:zod@^3.25.76";
var list_stories_default = defineTool({
  name: "list_stories",
  title: "List stories",
  description: "List published stories on Dolphoon with title, category, and premium status.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Max stories to return."),
    category: z.string().optional().describe("Filter by category slug or name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    let query = supabase.from("stories").select("id, title, category, is_premium, is_published").eq("is_published", true).limit(limit);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { stories: data }
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.49.8";
import { z as z2 } from "npm:zod@^3.25.76";
var list_courses_default = defineTool2({
  name: "list_courses",
  title: "List courses",
  description: "List published courses on Dolphoon.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(20).describe("Max courses to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("courses").select("id, title, description, is_premium, is_published").eq("is_published", true).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { courses: data }
    };
  }
});

// src/lib/mcp/tools/search-content.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.49.8";
import { z as z3 } from "npm:zod@^3.25.76";
var search_content_default = defineTool3({
  name: "search_content",
  title: "Search content",
  description: "Search published stories and courses on Dolphoon by title keyword.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Keyword to search titles for."),
    limit: z3.number().int().min(1).max(25).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const pattern = `%${query}%`;
    const [stories, courses] = await Promise.all([
      supabase.from("stories").select("id, title, is_premium").eq("is_published", true).ilike("title", pattern).limit(limit),
      supabase.from("courses").select("id, title, is_premium").eq("is_published", true).ilike("title", pattern).limit(limit)
    ]);
    const result = { stories: stories.data ?? [], courses: courses.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dolphoon-mcp",
  title: "Dolphoon",
  version: "0.1.0",
  instructions: "Browse Dolphoon's published stories, courses, and content library for kids. Use `list_stories` and `list_courses` to enumerate content, or `search_content` to search by title keyword.",
  tools: [list_stories_default, list_courses_default, search_content_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
