// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brxbtgzaumryxflkykpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyeGJ0Z3phdW1yeXhmbGt5a3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzQ1NjMsImV4cCI6MjA2MzUxMDU2M30.8Y7wwEkyBmOy_wvzZUIYIzd2PE1MOrT8a25I2k9r1Cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);